os: linux
dist: xenial
language: node_js
node_js:
   - "12"
install:
    - npm install
    - npm install jsdom
    - npm install -g http-server
    - npm install -g mocha
    - npm install eslint
    - npm install eslint-config-google

stages:
  - name: tests
  - name: lintjs
  - name: linthtml

before_script:
  - npm start & # start the service
  - sleep 3 # give some time to bind to sockets, etc

jobs:
  include:
    - stage: tests
      name: Unit Tests
      script: npm run-script test
    - stage: lintjs
      name: "JS Code Style Check"
      script: npm run-script lint
